# Generated by Django 5.1.7 on 2025-03-11 12:55

import data.custom_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoria",
            name="codigo",
        ),
        migrations.AddField(
            model_name="categoria",
            name="porcentaje_iva",
            field=data.custom_fields.CustomIntegerField(
                default="19", verbose_name="Porcentaje IVA"
            ),
        ),
    ]
