# Generated by Django 5.1.7 on 2025-03-19 01:05

import data.custom_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0003_detalleventa_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actividadcaja",
            name="monto",
            field=data.custom_fields.CustomMoneyField(verbose_name="Monto"),
        ),
        migrations.AlterField(
            model_name="caja",
            name="monto_apertura",
            field=data.custom_fields.CustomMoneyField(verbose_name="Monto Apertura"),
        ),
        migrations.AlterField(
            model_name="caja",
            name="monto_cierre",
            field=data.custom_fields.CustomMoneyField(
                blank=True, null=True, verbose_name="Monto Cierre"
            ),
        ),
        migrations.AlterField(
            model_name="detalleventa",
            name="precio",
            field=data.custom_fields.CustomMoneyField(verbose_name="Precio"),
        ),
        migrations.AlterField(
            model_name="detalleventa",
            name="total",
            field=data.custom_fields.CustomMoneyField(default=0, verbose_name="Total"),
        ),
        migrations.AlterField(
            model_name="venta",
            name="total",
            field=data.custom_fields.CustomMoneyField(verbose_name="Total"),
        ),
    ]
