# Generated by Django 5.2 on 2025-04-17 16:49

import data.custom_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_detalleventa_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='numero',
            field=data.custom_fields.CustomIntegerField(default=0, unique=True, verbose_name='Número'),
        ),
    ]
