# Generated by Django 5.2 on 2025-04-20 10:58

import data.custom_fields
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comun', '0002_alter_usuario_options'),
        ('ventas', '0008_caja_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='venta',
            field=data.custom_fields.CustomForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_venta', to='ventas.venta', verbose_name='Venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='usuario',
            field=data.custom_fields.CustomForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comun.usuario', verbose_name='Usuario'),
        ),
    ]
