# Generated by Django 5.1.7 on 2025-03-11 14:58

import data.custom_fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    data.custom_fields.CustomAutoField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    data.custom_fields.CustomCharField(
                        max_length=100, verbose_name="Nombre"
                    ),
                ),
                (
                    "descripcion",
                    data.custom_fields.CustomCharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "activo",
                    data.custom_fields.CustomBooleanField(
                        default=True, verbose_name="Activo"
                    ),
                ),
                (
                    "porcentaje_iva",
                    data.custom_fields.CustomIntegerField(
                        default="19", verbose_name="Porcentaje IVA"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    data.custom_fields.CustomAutoField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    data.custom_fields.CustomCharField(
                        max_length=10,
                        validators=[django.core.validators.MinLengthValidator(3)],
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    data.custom_fields.CustomCharField(
                        max_length=100, verbose_name="Nombre"
                    ),
                ),
                (
                    "descripcion",
                    data.custom_fields.CustomCharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "precio_compra",
                    data.custom_fields.CustomIntegerField(verbose_name="Precio Compra"),
                ),
                (
                    "precio_venta",
                    data.custom_fields.CustomIntegerField(verbose_name="Precio Venta"),
                ),
                ("stock", data.custom_fields.CustomIntegerField(verbose_name="Stock")),
                (
                    "activo",
                    data.custom_fields.CustomBooleanField(
                        default=True, verbose_name="Activo"
                    ),
                ),
                (
                    "categoria",
                    data.custom_fields.CustomForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventario.categoria",
                        verbose_name="Categoría",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
            },
        ),
    ]
