# Generated by Django 5.1.7 on 2025-04-02 02:13

import data.custom_fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0002_alter_producto_precio_compra_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoria",
            options={
                "ordering": ["-id"],
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
            },
        ),
        migrations.AlterModelOptions(
            name="producto",
            options={
                "ordering": ["-id"],
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
            },
        ),
        migrations.RemoveField(
            model_name="producto",
            name="descripcion",
        ),
        migrations.AddField(
            model_name="producto",
            name="codigo_barras",
            field=data.custom_fields.CustomCharField(
                blank=True, max_length=20, null=True, verbose_name="Código de Barras"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="activo",
            field=data.custom_fields.CustomBooleanField(
                blank=True, default=True, null=True, verbose_name="Activo"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="codigo",
            field=data.custom_fields.CustomCharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[django.core.validators.MinLengthValidator(3)],
                verbose_name="Código",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio_compra",
            field=data.custom_fields.CustomMoneyField(
                blank=True, null=True, verbose_name="Precio Compra"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="stock",
            field=data.custom_fields.CustomIntegerField(
                blank=True, default=0, null=True, verbose_name="Stock"
            ),
        ),
    ]
