# Generated by Django 5.1.7 on 2025-03-11 14:57

import data.custom_fields
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    data.custom_fields.CustomAutoField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    data.custom_fields.CustomCharField(
                        max_length=100, verbose_name="Nombre"
                    ),
                ),
                (
                    "email",
                    data.custom_fields.CustomEmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "activo",
                    data.custom_fields.CustomBooleanField(
                        default=True, verbose_name="Activo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
            },
        ),
    ]
