# Generated by Django 5.1.7 on 2025-04-02 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comun", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usuario",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
            },
        ),
    ]
