# Generated by Django 5.1.7 on 2025-03-13 18:44

import data.custom_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="state",
            field=data.custom_fields.CustomCharField(
                blank=True,
                choices=[("BR", "Borrador"), ("CR", "Creada"), ("AN", "Anulada")],
                default="BR",
                max_length=3,
                null=True,
                verbose_name="Estado",
            ),
        ),
    ]
