# Generated by Django 5.1.7 on 2025-03-16 22:06

import data.custom_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0002_venta_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="detalleventa",
            name="total",
            field=data.custom_fields.CustomIntegerField(
                default=0, verbose_name="Total"
            ),
        ),
    ]
