# Generated by Django 5.1.7 on 2025-04-02 02:13

import data.custom_fields
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comun", "0002_alter_usuario_options"),
        ("ventas", "0004_alter_actividadcaja_monto_alter_caja_monto_apertura_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actividadcaja",
            options={
                "ordering": ["-id"],
                "verbose_name": "Actividad Caja",
                "verbose_name_plural": "Actividad Cajas",
            },
        ),
        migrations.AlterModelOptions(
            name="caja",
            options={
                "ordering": ["-id"],
                "verbose_name": "Caja",
                "verbose_name_plural": "Cajas",
            },
        ),
        migrations.AlterModelOptions(
            name="detalleventa",
            options={
                "ordering": ["-id"],
                "verbose_name": "Detalle Venta",
                "verbose_name_plural": "Detalle Ventas",
            },
        ),
        migrations.AlterModelOptions(
            name="venta",
            options={
                "ordering": ["-id"],
                "verbose_name": "Venta",
                "verbose_name_plural": "Ventas",
            },
        ),
        migrations.RemoveField(
            model_name="actividadcaja",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="actividadcaja",
            name="fecha",
        ),
        migrations.RemoveField(
            model_name="actividadcaja",
            name="monto",
        ),
        migrations.RemoveField(
            model_name="caja",
            name="fecha_apertura",
        ),
        migrations.RemoveField(
            model_name="caja",
            name="fecha_cierre",
        ),
        migrations.RemoveField(
            model_name="caja",
            name="monto_apertura",
        ),
        migrations.RemoveField(
            model_name="caja",
            name="monto_cierre",
        ),
        migrations.RemoveField(
            model_name="caja",
            name="usuario_apertura",
        ),
        migrations.RemoveField(
            model_name="caja",
            name="usuario_cierre",
        ),
        migrations.AddField(
            model_name="actividadcaja",
            name="fecha_apertura",
            field=data.custom_fields.CustomDateTimeField(
                default=None, verbose_name="Fecha Apertura"
            ),
        ),
        migrations.AddField(
            model_name="actividadcaja",
            name="fecha_cierre",
            field=data.custom_fields.CustomDateTimeField(
                blank=True, null=True, verbose_name="Fecha Cierre"
            ),
        ),
        migrations.AddField(
            model_name="actividadcaja",
            name="monto_apertura",
            field=data.custom_fields.CustomMoneyField(
                blank=True, default=0, null=True, verbose_name="Monto Apertura"
            ),
        ),
        migrations.AddField(
            model_name="actividadcaja",
            name="monto_cierre",
            field=data.custom_fields.CustomMoneyField(
                blank=True, default=0, null=True, verbose_name="Monto Cierre"
            ),
        ),
        migrations.AddField(
            model_name="actividadcaja",
            name="usuario",
            field=data.custom_fields.CustomForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuario",
                to="comun.usuario",
                verbose_name="Usuario Apertura",
            ),
        ),
        migrations.AlterField(
            model_name="actividadcaja",
            name="caja",
            field=data.custom_fields.CustomForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="ventas.caja",
                verbose_name="Caja",
            ),
        ),
        migrations.AlterField(
            model_name="caja",
            name="activo",
            field=data.custom_fields.CustomBooleanField(
                blank=True, default=True, null=True, verbose_name="Activo"
            ),
        ),
    ]
