# Generated by Django 5.1.7 on 2025-04-02 14:44

import data.custom_fields
import datetime
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0003_alter_categoria_options_alter_producto_options_and_more"),
        ("ventas", "0005_alter_actividadcaja_options_alter_caja_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalleventa",
            name="producto",
            field=data.custom_fields.CustomForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="inventario.producto",
                verbose_name="Producto",
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="caja",
            field=data.custom_fields.CustomForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="ventas.caja",
                verbose_name="Caja",
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="fecha",
            field=data.custom_fields.CustomDateTimeField(
                default=datetime.datetime.now, verbose_name="Fecha"
            ),
        ),
    ]
